### ISSUE TITLE
libsignal-protocol-java not working on protobuf 3.22.0

### ISSUE THREAD

**Issue by ashifali3147** [signalapp/libsignal#582]
I am working on a project which using 
`implementation 'org.whispersystems:signal-protocol-java:2.8.1'`

Now the problem is this is using an old protobuf library 3.10.0

To use this  libsignal-protocol-java i have to use below code

`configurations {
    configureEach {
        resolutionStrategy {
            force group: 'com.google.protobuf', name: 'protobuf-javalite', version: '3.10.0'
        }
    }
}`

then it's working fine, but other libary using latest protobuf library 3.22.0 and higher, but if i removing this resolutionStrategy then getting

Error:

Process: com.app.package, PID: 12793
                 java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.String
                    at com.google.protobuf.MessageSchema.newSchemaForRawMessageInfo(MessageSchema.java:507)
                    at com.google.protobuf.MessageSchema.newSchema(MessageSchema.java:227)
                    at com.google.protobuf.ManifestSchemaFactory.newSchema(ManifestSchemaFactory.java:77)
                    at com.google.protobuf.ManifestSchemaFactory.createSchema(ManifestSchemaFactory.java:71)
                    at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:90)
                    at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:104)
                    at com.google.protobuf.GeneratedMessageLite.makeImmutable(GeneratedMessageLite.java:175)
                    at com.google.protobuf.GeneratedMessageLite$Builder.buildPartial(GeneratedMessageLite.java:397)
                    at com.google.protobuf.GeneratedMessageLite$Builder.build(GeneratedMessageLite.java:405)
                    at org.whispersystems.libsignal.state.SessionState.<init>(SessionState.java:46)
                    at org.whispersystems.libsignal.state.SessionRecord.<init>(SessionRecord.java:25)
                    
Is there any way to use both protobuf version in the same project. Or is there any way to update  libsignal-protocol-java this libary.

**Comment by jrose-signal** [comment]
I'm afraid any use outside of Signal isn't officially supported. You can ask further questions on https://community.signalusers.org and see if anyone else has had the same issues.
